# Generated by Django 3.2 on 2022-03-09 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_archivedocument_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.archivedocument'),
        ),
    ]
