# Generated by Django 3.2 on 2022-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220309_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='subfolder',
            field=models.ManyToManyField(blank=True, related_name='_core_folder_subfolder_+', to='core.Folder'),
        ),
    ]
