# Generated by Django 3.2 on 2022-03-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_folder_subfolder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
