# Generated by Django 3.2 on 2022-03-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
